### ISSUE TITLE
No ROCmLibs.zip file

### ISSUE THREAD

**Issue by filemon11** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#15]
The readme states: "Grab the ROCmLibs.zip file and the rocm gfx1103 AMD780M phoenix V3 for hip sdk 5.7.7z (originally ROCmLibsgfx1103.zip) from this repository." There is no ROCmLibs.zip in this repository.

**Comment by likelovewant** [comment]
it's was an old message ,now the `zip` change to `7z` for small size .` ROCmLibs.zip` came with arch title , eg ROCmlibs , rocm gfx1103 AMD780M phoenix V3.  simply download v3 for hip5.7 , while v4 for hip 6.1.2 on windows. also other arches available at the release page.
