### ISSUE TITLE
Weird Output in LMS 0.3.5 with `win-llama-rocm-0.2.31`

### ISSUE THREAD

**Issue by gchriswill** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#16]
![Screenshot 2024-11-10 000712](https://github.com/user-attachments/assets/fee095be-aa54-48c7-8626-28b733677e54)

---

![Screenshot 2024-11-10 020119](https://github.com/user-attachments/assets/67b73a20-8a55-4f2d-a067-f4ec62cfee2a)

---

![Screenshot 2024-11-10 020202](https://github.com/user-attachments/assets/88f7b137-b80c-4b27-8670-924850bcf0e7)

--- 

- **Followed Guide:** https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/wiki/Unlock-LM-Studio-on-Any-AMD-GPU-with-ROCm-Guide

---

- **Followed issue solution:** https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/issues/11

---

**Software Stack:**

- LMS 0.3.5 + ROCm Llama.cpp 1.1.5 (Manually added)
- HIP SDK 5.7
- ROCmLibs for 5.7
- Ollama For AMD 0.3.6
- AMD Radeon Software 24.10.1

---

**Hardware Stack:**

OS: Windows 11 (23H2)
CPU: Intel Core i3-10100
RAM: Crucial PRO 32GB
Storage: Crucial BX SATA SSD 250 GB
GPUs: 6x - AMD XFX Merc RX6700XT

---

Being 2 days going back and forth trying to have LM Studio + ROCm + 6x 6700XT. I got to the point of LM Studio recognizing the GPUs (Proven at third screenshot of LMS System Resources with 72GB of VRAM), and being able to get compatible status for the llama-ROCm runtime (Proven at second screenshot), and even loading different models. But the responses seems to be machine code or some sort of combination/mix from text response and code.

@likelovewant, Any suggestions/ideas of what might be the issue?

Thanks in advance 🙏

**Comment by likelovewant** [comment]
Try ROCmLibs for 6.1.2, LM studio had updated it , if still talking no sense , try different ollama for amd version.
@gchriswill

**Comment by gchriswill** [comment]
@likelovewant Ok, will try the following **Software Stack**:

- LMS 0.3.5 + ROCm Llama.cpp 1.1.10 (from LMS runtimes)
- HIP SDK 6.1.0
- ROCmLibs for 6.1.2
- Ollama For AMD 0.4.1
- AMD Radeon Software 24.10.1

---

I will delete and reset everything to have a clean and fresh start to triage the stack with the updated versions, and post back the results in this issue thread. 👍

**Comment by gchriswill** [comment]
@likelovewant Also, just for informational purposes here is another interesting scenario from my setup in a ticket I submitted to LMS repo.
`https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/194` (Unliked due to is unrelated)

**Comment by likelovewant** [comment]
> @likelovewant Ok, will try the following **Software Stack**:
> 
> * LMS 0.3.5 + ROCm Llama.cpp 1.1.10 (from LMS runtimes)
> * HIP SDK 6.1.0
> * ROCmLibs for 6.1.2
> * Ollama For AMD 0.4.1
> * AMD Radeon Software 24.10.1
> 
> I will delete and reset everything to have a clean and fresh start to triage the stack with the updated versions, and post back the results in this issue thread. 👍

1,` ROCmLibs for 6.1.2` don't work with` Ollama For AMD 0.4.1 `as it was build with `Rocm5.7`. and there is an breaking change in ollama  0.4.0 and then after . try earlier version . test works with` v0.3.14 `. simply rename ollama` ggml.dll `to `ggml_llamacpp.dll` and replace the dll files in LMS0.3.5 and ROCmlibs.

2,* HIP SDK 6.1.0 is not a necessary . As  the ROCm libs direct talk to AMD drivers ,ie AMD Radeon Software.

3, make sure to read the release notes . some build rocm 5.7 ,others build with 6.1. need compitable rocmbs . however ,those trick are changing as the new update in lmstudio or ollama . it's may break anytime.

**Comment by likelovewant** [comment]
> @likelovewant Also, just for informational purposes here is another interesting scenario from my setup in a ticket I submitted to LMS repo. `https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/194` (Unliked due to is unrelated)

In ollama , there can be mannuly set `gpu_num` offload , lmstudio set all depend on their update .

@gchriswill

**Comment by likelovewant** [comment]
This method stop working in the new update ollama and then after , close this now .
