### ISSUE TITLE
Installation Step 3.3 Confusion

### ISSUE THREAD

**Issue by edwrdcrpio** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#17]
Here's how I interpreted your guidance.
1. Excuse my novice knowledge, but I assumed the %HIP_PATH%\bin\rocblas is C:\Program Files\AMD\ROCm\6.1\bin\ and that's where the "rocblas" folder is in, and the rocblas folder is called library and I renamed it to oldlibrary. Then I extracted the contents inside "gfx1103 AMD780M phoenix V4 for hip sdk 6.1.2" into C:\Program Files\AMD\ROCm\6.1\bin\ and confirming the overwrite of the rocblas.dll file. Now I have library and oldlibrary folders.
2. I took the rocblas.dll file from the folder "gfx1103 AMD780M phoenix V4 for hip sdk 6.1.2" and place it inside C:\Program Files\AMD\ROCm\6.1\bin\ and confirming the overwrite. (which I already did in the previous step)
3. I renamed the recently transferred folder called "library" (that came from gfx1103 AMD780M phoenix V4 for hip sdk 6.1.2) to "origlibrary"
4. I again extracted the contents from "gfx1103 AMD780M phoenix V4 for hip sdk 6.1.2" (which I did already in step 1). So now the rocblas.dll file was overwritten 3 times and now I have library, oldlibrary, and origlibrary folders and technically library and origlibrary is the same.

I don't see a time difference in generating images using SD1.5 Automatic1111. I do not get any errors. Did I misunderstand the steps? 

Thank you for the help and I apologize for my lack of experience!

**3. Installation:**
1. Unzip ROCmLibs.zip or 7z. Place the extracted library folder into your %HIP_PATH%\bin\rocblas directory, renaming the existing "rocblas" folder (e.g., to "oldlibrary").
2. Copy the rocblas.dll file from the downloaded ROCmLibs.zip or 7z into the rocblas\library folder within your %HIP_PATH%\bin directory (example: C:\Program Files\AMD\ROCm\5.7\bin). Replace the original file.
3. Rename your existing "rocblas\library" folder (e.g., to "origlibrary").
4. Extract the contents of rocm gfx1103 AMD780M phoenix V3 for hip sdk 5.7.7z into the same directory where you placed the ROCmLibs folder.

**Comment by likelovewant** [comment]
> Or did I miss the pre-requisite of not installing ZLUDA from github.com/lshqqytiger?

if you choose to work with hip6.1.2 . Then you should choose lshqqytiger version of zluda . However it's automatically download in most case by add --use-zluda . The speed for 5.7 and 6.1 is same . The speed boost is only happens when compared to directml. If you test automatic,check lshqqytiger's stable diffusion for amd gpu.

**Comment by edwrdcrpio** [comment]
Thanks for the quick response! So I'll need lshqqytiger's SD for AMD along with your ROCmLibs? Just for context I have a 780M with the 8745HS. From my understanding ZULDA doesn't have support for 780M yet, which is why I'm using your package.

I appreciate your guidance!

**Comment by likelovewant** [comment]
> Thanks for the quick response! So I'll need lshqqytiger's SD for AMD along with your ROCmLibs? Just for context I have a 780M with the 8745HS. From my understanding ZULDA doesn't have support for 780M yet, which is why I'm using your package.
> 
> 
> 
> I appreciate your guidance!

zluda need to work with rocm . However,780M is not official suppprted by rocm . Had to build that lib . Replace and get it support . The build guide available at the wiki of these release. Feel free to test it.

@edwrdcrpio
