### ISSUE TITLE
gfx1150 not run

### ISSUE THREAD

**Issue by piDack** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#18]
I use gfx1150 library with rocblos 6.1.2 dll or 6.2.0.dll not work

![image](https://github.com/user-attachments/assets/263ba11b-13d5-411b-8a84-12abd90010ed)

**Comment by likelovewant** [comment]
Any lucky success for this ? This is new and nobody have test it

**Comment by likelovewant** [comment]
> > Any lucky success for this ? This is new and nobody have test it
> 
> Yes, I managed to successfully run it on llama.cpp on 890M iGPU. Everything seems to be working smoothly!

great，confirmed it works .
