### ISSUE TITLE
gfx1010 (RX 5700 XT) frequently dying in ollama runner (Windows) with no error message

### ISSUE THREAD

**Issue by rbuccigrossi** [likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU#5]
This is probably an issue in ollama for Windows, but since your wonderful libraries are the only way to run older AMD cards, I wanted to document it here to help others.

I have a Radeon RX 5700 XT.  Using rocBLAS-HIP5.7.1-win.rar or your brand new rocblas for gfx1010 xnack- with building guide.7z, I am able to get it to work with ollama for Windows by setting (I have an xnack card too so I need to force identification):

$Env:HSA_OVERRIDE_GFX_VERSION = "10.1.0"
$Env:HCC_AMDGPU_TARGET = "gfx1010"

Tiny LLMs (like tinyllama:latest or gwen2:1.5b) work perfectly.

Larger LLMs (like llama3:8b) crash 3 out of 4 times:

```
C:\Users\Butch>ollama run llama3
Error: llama runner process has terminated: exit status 0xc0000005

C:\Users\Butch>ollama run llama3
>>> Please say something about yourself.
Nice to meet you!

I am LError: error reading llm response: read tcp 127.0.0.1:56023->127.0.0.1:56017: wsarecv: An existing connection was forcibly closed by the remote host.
```

But with persistence will eventually work:

```
C:\Users\Butch>ollama run llama3
>>> Please say something about yourself.
I'm just an AI, so I don't have personal experiences or feelings like humans do. I exist solely to process and
generate text based on the inputs I receive.

I was created through a process called deep learning, which involves training artificial neural networks on large
amounts of data. My training data includes a vast corpus of text from the internet, books, and other sources,
which allows me to learn about language patterns, syntax, and semantics.

I don't have personal opinions or biases, but I'm designed to be helpful and informative. I can answer questions,
provide definitions, summarize texts, translate languages, and even generate creative writing like stories or
poetry. My goal is to assist users in understanding and communicating effectively, while also continuing to learn
and improve my abilities.

So, that's me in a nutshell!

>>> 
```

The problem is that no errors appear on the server log (I run "ollama serve" on the command line so I see the errors), so it is hard to diagnose what is going wrong.  I can get llama3:8b to be reliable by using "/set parameter num_gpu 9". But of course running 9 out of 33 layers on the GPU is slow.

Any ideas or things I can do to help diagnose the situation?

**Comment by rbuccigrossi** [comment]
Hunting around the HIP How To Guides on debugging, I found that I can set the environment variable  "AMD_LOG_LEVEL" to "1" for errors and "2" for info. I get a lot more information, but unfortunately it doesn't show me any specific error when the runner dies. So alas, no new clues.

**Comment by likelovewant** [comment]
> $Env:HSA_OVERRIDE_GFX_VERSION = "10.1.0"
> $Env:HCC_AMDGPU_TARGET = "gfx1010"

update with gfx1010:xanck- support in new release .remove those setting` $Env:HSA_OVERRIDE_GFX_VERSION = "10.1.0" .$Env:HCC_AMDGPU_TARGET = "gfx1010" `.  install and replace rocblibs for gfx .   simply run `ollama run llama3 ` .

Sometimes , the force exist was due to the limits of vram .Make sure you have enough vram for the model .

**Comment by rbuccigrossi** [comment]
Thank you! 

Just to warn you, the current renamed version of  "rocblas for gfx1010: xnack- with building guide.7z" is currently 0 bytes long ( https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/blob/main/rocblas%20for%20gfx1010%3A%20xnack-%20with%20building%20guide.7z )

**Comment by likelovewant** [comment]
> Thank you!
> 
> Just to warn you, the current renamed version of "rocblas for gfx1010: xnack- with building guide.7z" is currently 0 bytes long ( https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/blob/main/rocblas%20for%20gfx1010%3A%20xnack-%20with%20building%20guide.7z )

thanks for your reminding . fixed it .

**Comment by rbuccigrossi** [comment]
I'm probably doing something wrong because even with your new gfx1010:xnack- libraries I'm getting the error:

time=2024-07-02T12:51:33.052-04:00 level=WARN source=amd_windows.go:97 msg="amdgpu is not supported" gpu=0 gpu_type=gfx1010:xnack- library=C:\Users\Butch\AppData\Local\Programs\Ollama\rocm supported_types=[gfx1010]

To double check, I'm:

- Replacing the contents of "C:\Users\Butch\AppData\Local\Programs\Ollama\rocm\rocblas\library with rocblas\library" with "gfx1010- xnack- with building guide.7z\library"
- Replacing "C:\Users\Butch\AppData\Local\Programs\Ollama\rocm\rocblas.dll" with "rocblas for gfx1010- xnack- with building guide.7z\rocblass.dll"

And then running "ollama serve".  Is there anything else I should be doing to set up the library correctly?

**Comment by likelovewant** [comment]
> I'm probably doing something wrong because even with your new gfx1010:xnack- libraries I'm getting the error:
> 
> 
> 
> time=2024-07-02T12:51:33.052-04:00 level=WARN source=amd_windows.go:97 msg="amdgpu is not supported" gpu=0 gpu_type=gfx1010:xnack- library=C:\Users\Butch\AppData\Local\Programs\Ollama\rocm supported_types=[gfx1010]
> 
> 
> 
> To double check, I'm:
> 
> 
> 
> - Replacing the contents of "C:\Users\Butch\AppData\Local\Programs\Ollama\rocm\rocblas\library with rocblas\library" with "gfx1010- xnack- with building guide.7z\library"
> 
> - Replacing "C:\Users\Butch\AppData\Local\Programs\Ollama\rocm\rocblas.dll" with "rocblas for gfx1010- xnack- with building guide.7z\rocblass.dll"
> 
> 
> 
> And then running "ollama serve".  Is there anything else I should be doing to set up the library correctly?

Fully close the ollama , install the new release Ollama V0.1.48-alpha-2 . It's seems you are testing with an older version which only support gfx1010. Replace the file . Then simply run " ollama run llama"

**Comment by rbuccigrossi** [comment]
Are you referring to a v0.1.49-alpha-2 version? I am already running v0.1.48. For good measure I uninstalled and grabbed the latest ollama for Windows from the web site and see (in the server logs):

time=2024-07-02T13:58:56.784-04:00 level=INFO source=routes.go:1111 msg="Listening on 127.0.0.1:11434 **(version 0.1.48)**"
time=2024-07-02T13:58:57.097-04:00 level=WARN source=amd_windows.go:97 msg="amdgpu is not supported" gpu=0 gpu_type=gfx1010:xnack- library=C:\Users\Butch\AppData\Local\Programs\Ollama\rocm supported_types="[gfx1030 gfx1100 gfx1101 gfx1102 gfx906]"

**Comment by likelovewant** [comment]
> Are you referring to a v0.1.49-alpha-2 version? I am already running v0.1.48. For good measure I uninstalled and grabbed the latest ollama for Windows from the web site and see (in the server logs):
> 
> 
> 
> time=2024-07-02T13:58:56.784-04:00 level=INFO source=routes.go:1111 msg="Listening on 127.0.0.1:11434 **(version 0.1.48)**"
> 
> time=2024-07-02T13:58:57.097-04:00 level=WARN source=amd_windows.go:97 msg="amdgpu is not supported" gpu=0 gpu_type=gfx1010:xnack- library=C:\Users\Butch\AppData\Local\Programs\Ollama\rocm supported_types="[gfx1030 gfx1100 gfx1101 gfx1102 gfx906]"

Apparently, it's now change to other supported arches. gfx1030...gfx1102 which came from ollama official . Download now from ollama for amd for version tag v-1.48-alpha-2 (the actual tag would alpha-4 , if you type in the terminal with " ollama -v".otherwise, you download a wrong version or clicked the update pop up by ollama . It's from ollama official, it has limited support arches. Also. Try to replace the rocblas file and library in hip sdk . That's might be another reason causing the errors.

**Comment by rbuccigrossi** [comment]
Oh thank you! I didn't realize you did the legwork and released your own copy. That explains why you and I were having such different experiences...
